name: Build & Publish

on:
  push:
    branches:
      - "*"
      - "!dependabot/*"
  workflow_dispatch:


jobs:
  next-build:
    runs-on: ubuntu-latest
    container: node:23-alpine3.20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
        working-directory: ./ivm_app
      - run: npm run build
        working-directory: ./ivm_app
      - name: List files
        run: |
          echo "Listing files in the current directory:"
          ls -al
          echo "Listing files in the .next directory:"
          ls -al .next
          echo "Listing files in the public directory:"
          ls -al public
          echo "Listing files in the ivm_app directory:"
          ls -al ivm_app
      - name: Upload Next build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .next
            public
          retention-days: 30
  docker-push:
    needs: next-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Next build
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push Docker image
        run: |
          export CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          export TAG=$([[ $CURRENT_BRANCH == "main" ]] && echo "latest" || echo $CURRENT_BRANCH)
          export GITHUB_REF_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
          export GITHUB_BRANCH_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$TAG
          docker build -t $GCR_IMAGE -t $GITHUB_REF_IMAGE -t $GITHUB_BRANCH_IMAGE
          echo "Pushing Image to GitHub Container Registry"
          docker push $GITHUB_REF_IMAGE
          docker push $GITHUB_BRANCH_IMAGE

  