name: Build & Publish

on:
  push:
    branches:
      - "*"
      - "!dependabot/*"
  workflow_dispatch:

jobs:
  next-build:
    runs-on: ubuntu-latest
    container: node:24-alpine3.21
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: npm
        working-directory: ./ivm_app
        run: |
          npm ci
          npm run build
      - name: List files
        run: |
          echo "Listing files in ivm_app/.next:"
          ls -alR ivm_app/.next
          echo "Listing files in ivm_app/public:"
          ls -alR ivm_app/public
      - name: Upload Next build
        uses: actions/upload-artifact@v4
        with:
          name: ivm_app_build
          include-hidden-files: true
          path: |
            ivm_app/.next
            ivm_app/public
          retention-days: 7
  docker-push:
    needs: next-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Next build
        uses: actions/download-artifact@v4
        with:
          name: ivm_app_build
          path: ivm_app
      - name: Post-download dir
        run: |
          set -x
          pwd
          ls -a
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          set -x
          pwd
          ls -a
          cd ivm_app
          ls -a
          export CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          export TAG=$([[ $CURRENT_BRANCH == "main" ]] && echo "latest" || echo $CURRENT_BRANCH)
          REPO="${GITHUB_REPOSITORY,,}"
          export GITHUB_REF_IMAGE=ghcr.io/$REPO:$GITHUB_SHA
          export GITHUB_BRANCH_IMAGE=ghcr.io/$REPO:$TAG
          docker build -t $GITHUB_REF_IMAGE -t $GITHUB_BRANCH_IMAGE .
          echo "Pushing Image to GitHub Container Registry"
          docker push $GITHUB_REF_IMAGE
          docker push $GITHUB_BRANCH_IMAGE
